---
- name: Converge
  hosts: all
  become: true
  vars:
    hosts_file: "/tmp/hosts"
    add_inventory_host: true
    hosts_definitions:
      - address: 172.1.2.3
        hostnames:
          - lala

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false


  roles:
    - role: jvzantvoort.hosts
